name: LLM Stack

services:
  ollama:
    image: docker.io/ollama/ollama:0.13.5
    volumes:
      - ${BASE_STACK_DIR}/models:/root/.ollama
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
    ports:
      - '11434:11434'
    networks:
      - proxy_net
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "ollama serve & sleep 5 && ollama pull hf.co/akjindal53244/Llama-3.1-Storm-8B-GGUF:Q4_K_M  && ollama pull pedrovillalobos/mxbai-embed-large-no-gpu:latest && ollama pull phi3:3.8b-mini-4k-instruct-q4_K_M && wait",
      ]
    restart: always

networks:
  proxy_net:
    external: true
    name: network_backend_net
