name: LLM Stack

services:
  ollama:
    image: intelanalytics/ipex-llm-inference-cpp-xpu:2.3.0-SNAPSHOT
    volumes:
      - ${BASE_STACK_DIR}/models:/root/.ollama
      - ./entry.sh:/entry.sh
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=Europe/Berlin
      - no_proxy=localhost,127.0.0.1
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_INTEL_GPU=true
      - OLLAMA_NUM_GPU=999
      - DEVICE=iGPU
      - ZES_ENABLE_SYSMAN=1 
      - OLLAMA_NUM_PARALLEL=1

    ports:
      - '11434:11434'
    networks:
      - proxy_net
    entrypoint:
      [ "/bin/bash", "-c", "/entry.sh" ]
    restart: always

networks:
  proxy_net:
    external: true
    name: network_backend_net
