name: LLM Stack

services:
  ollama:
    image: docker.io/ollama/ollama:0.13.5
    depends_on:
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
    ports:
      - '11434:11434'
    command: >
      ollama pull llama3.2:1b &&
      ollama serve
   networks:
      - proxy_net
    restart: always
    links:

networks:
  proxy_net:
    external: true
    name: network_backend_net
