name: LLM Stack

services:
  ollama:
    image: docker.io/ollama/ollama:0.13.5
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
    ports:
      - '11434:11434'
    networks:
      - proxy_net
    command: /bin/sh -c "ollama pull llama3.2:1b && ollama serve"
    restart: always

networks:
  proxy_net:
    external: true
    name: network_backend_net
